// GENERATED by scripts/sync-conditions-core.mjs — edit src/shared/conditions-core, do not edit here

// conditions-core / evaluator.ts
//
// The GENERIC HEADLESS EVALUATOR. This is the headless half's runtime engine:
// given a list of ConditionModules and a per-tick set of `inputs`, it produces
// the unified ConditionSnapshot that goes over the wire, and it owns the
// change-detection (dedupe) that decides whether a snapshot is worth emitting.
//
// WHY this file exists
// --------------------
// Before this, each provider's headless package re-implemented the SAME loop by
// hand: call each builder, drop the nulls, stuff the survivors into a `conditions`
// map keyed by `kind`, JSON.stringify it to dedupe, then emit. Codex did this in
// `evaluateCodexConditions` + `codexConditionSnapshotKey` + the dedupe latch
// inside `CodexHeadless.publishConditionSnapshot`. Claude will need the exact
// same shape next. Re-deriving identical glue per provider is how subtle drift
// (different key ordering, different dedupe semantics) creeps in. This evaluator
// is that glue, written ONCE, parameterized over the provider tag `P` and the
// per-provider input bundle `I`.
//
// WHY it's pure + clock-injected
// ------------------------------
// `now` is injected rather than calling `Date.now()` inline so the whole thing
// is deterministic and testable: the PR-2 byte-for-byte verification (a
// throwaway script that pinned `ts` to a fixed value and diffed the OLD and NEW
// serialized snapshots — run out-of-band, NOT committed, per the repo's
// no-committed-tests policy) relied on this, and any future test can do the
// same. The evaluator holds exactly one piece of mutable state —
// `lastKey` for dedupe — and nothing else; everything else is a pure function of
// its arguments.
//
// THE ONE INVARIANT THAT MUST NOT DRIFT: insertion order is observable.
// --------------------------------------------------------------------
// `keyOf` is `JSON.stringify(snapshot.conditions)`. JSON.stringify serializes a
// plain object's keys in INSERTION ORDER. The dedupe latch compares these
// strings verbatim. Therefore the order in which modules add their records to
// the `conditions` map is part of the wire contract: two snapshots with the same
// records inserted in a different order produce DIFFERENT keys and would be
// treated as a change. This mirrors the legacy Codex behavior exactly (trust
// inserted before approval). The caller's `modules` array order IS that
// insertion order — DO NOT sort, DO NOT reorder. See CODEX_MODULES.

import type {
  ConditionAction,
  ConditionCustomAction,
  ConditionModule,
  ConditionRecord,
  ConditionSnapshot,
} from './contract.js'

// The evaluator the factory returns. Generic over provider tag `P` and the
// per-provider input bundle `I` so a single implementation serves Codex, Claude,
// and anything later.
export type ConditionEvaluator<P extends string, I> = {
  // Run every module over `inputs` and assemble the snapshot. Pure apart from
  // reading the injected clock; does NOT touch the dedupe state (that's `changed`).
  evaluate: (inputs: I) => ConditionSnapshot<P>
  // The dedupe key for a snapshot. IDENTICAL to the legacy
  // `codexConditionSnapshotKey`: JSON.stringify of the `conditions` map only
  // (NOT `ts` — `ts` changes every tick and would defeat deduping). Insertion
  // order is load-bearing; see the file header.
  keyOf: (snapshot: ConditionSnapshot<P>) => string
  // Change-detection latch. Returns true (and updates the stored key) when `key`
  // differs from the last key passed in. This is the single mutable cell in the
  // evaluator; callers gate their emit on it exactly as the old latch did.
  changed: (key: string) => boolean
  // Route a `custom` action to the first module that can resolve it. Dormant
  // today (no live module defines `resolve`), present so the contract is whole.
  resolveAction: (
    action: ConditionCustomAction,
    ctx: unknown,
  ) => unknown | Promise<unknown>
}

export function makeEvaluator<P extends string, I>(
  provider: P,
  // `readonly` + the `any` state param: a module list is heterogeneous — each
  // module has its own concrete state type S, and there is no single S that
  // unifies them. The contract's ConditionModule<string, I, any> is the erased
  // form the evaluator routes over (it only ever reads `kind` and calls
  // `actions(state)`; it never inspects the state's shape), so erasing S to
  // `any` here is sound and matches how ConditionOutlet erases the view side.
  // The fourth `any` erases each module's resolver context too: a heterogeneous
  // registry can include modules with different live-driver handles, while the
  // evaluator only receives an opaque `ctx` and forwards it to the resolver that
  // opted in. The provider that constructs the evaluator owns making that ctx
  // match the modules it registers.
  modules: readonly ConditionModule<string, I, any, any>[],
  now: () => number,
): ConditionEvaluator<P, I> {
  // DEFENSIVE COPY of the module list. The caller hands us a `modules` array
  // (e.g. the exported CODEX_MODULES), and that array is a shared, importable
  // object that anything could push/splice/reorder after we're constructed.
  // Snapshotting it once here means a running evaluator's behavior — which
  // modules run, in what order — is frozen at construction and cannot be changed
  // out from under it by mutating the original array. Order is load-bearing (it
  // IS the insertion order of the conditions map, see the header invariant), so
  // a late reorder of the source array would otherwise silently drift the dedupe
  // key. `[...modules]` is a shallow copy, which is exactly right: we must not
  // clone the module objects themselves (their identity/closures matter), only
  // detach our iteration from the caller's array container. Every internal loop
  // below iterates `registry`, never `modules`.
  const registry = [...modules]

  // The dedupe cell. Seeded to '{}' so the FIRST evaluation of an empty
  // conditions map is correctly treated as "no change from the initial empty
  // snapshot" — matching CodexHeadless, whose `lastConditionKey` starts at '{}'
  // and whose initial `conditionSnapshot` is `{ conditions: {}, ts }`.
  let lastKey = '{}'

  function evaluate(inputs: I): ConditionSnapshot<P> {
    // Plain object, NOT a Map: JSON.stringify(conditions) must serialize in
    // insertion order for the dedupe key to be stable, and that's exactly what a
    // plain object gives us. Keys are added in module-array order below.
    const conditions: Record<string, ConditionRecord> = {}

    for (const module of registry) {
      const state = module.detect(inputs)
      // `detect` returning null means the condition is not live this tick — skip
      // it. (A module never emits a record for a condition that isn't present;
      // that's how the map stays "at most one record per live kind".)
      //
      // NOTE: we compare against `null` specifically, NOT a general falsy check.
      // A module's state could legitimately be a falsy-but-present value; the
      // contract's `detect: (I) => S | null` says null is the ONLY "not live"
      // sentinel, so that's the only thing we skip on.
      if (state === null) continue
      const actions: ConditionAction[] = module.actions(state)
      // Insertion happens HERE, in module order. This is the observable ordering
      // the dedupe key depends on. The record shape { kind, state, actions } is
      // exactly the legacy CodexCondition shape, so the serialized bytes match.
      conditions[module.kind] = { kind: module.kind, state, actions }
    }

    return {
      provider,
      conditions,
      ts: now(),
    }
  }

  function keyOf(snapshot: ConditionSnapshot<P>): string {
    // EXACTLY codexConditionSnapshotKey: stringify the conditions map, excluding
    // `ts`. Do not sort keys — see header invariant.
    return JSON.stringify(snapshot.conditions)
  }

  function changed(key: string): boolean {
    if (key === lastKey) return false
    lastKey = key
    return true
  }

  function resolveAction(
    action: ConditionCustomAction,
    ctx: unknown,
  ): unknown | Promise<unknown> {
    // Resolver modules return `undefined` when the action name is not theirs.
    // That keeps `name` as the routing key without forcing core to maintain a
    // separate name→module registry. It also prevents the first module that ever
    // grows a resolver (AUQ) from accidentally swallowing every future custom
    // action just because it appears earlier in registration order.
    for (const module of registry) {
      if (!module.resolve) continue
      const result = module.resolve(action, ctx)
      if (result !== undefined) return result
    }
  }

  return { evaluate, keyOf, changed, resolveAction }
}
